### ISSUE TITLE
Gloss location entry

### ISSUE THREAD

**Issue by cubap** [CenterForDigitalHumanities/Glossing-Matthew#37]
layout.html

Assign relative gloss location on the page as a tag or group of annotations for each page within a project. The annotations do not resolve which point to transcription lines, but with the Manifest in hand it can be known, so perhaps an additional reference `partOf` or something is called for.

The page should load existing layout on the screen when read in and there may be a case for a read only version of this page that is easier to catch a glance of for external use or to check your work.

**Comment by thehabes** [comment]
Use like http://localhost:8080/layout.html#http://t-pen.org/TPEN/manifest/7159 or http://localhost:8080/layout.html#http://tpentest.rerum.io/TPEN/manifest/7211

Is align-glosses.html connected with this?

**Comment by thehabes** [comment]
Assigning locations via the Annotation does stick.  I can also unassign lines from locations.  I can only do it for the first page of the Manifest though, so we need to be able to page turn.

The `target` is the Canvas (Folio) which is good.  
It also looks like a /query goes out for the Location Annotation each Canvas in the Manifest already.

When I have placed lines, but then delete them in TPEN, it does not cause an error on layout.html.  Any remaining lines I didn't delete are placed correctly.  No console errors.  The Annotation still remembers that it had those lines and where they were placed, which is no big deal.

**Comment by thehabes** [comment]
I think it is the `target` Canvas's job to do `partOf`.  We could do that if `target` was an embedded Canvas instead of a referenced one.  We need them resolving Canvases from TPEN.  The other option is to add a property to the Annotation that says `for the Canvas I target here is the Manifest it is a part of` but this feels like getting around how it is supposed to work.

**Comment by cubap** [comment]
I think there was a `f=` or `pageNum` param or something that opened to the page because the “edit layout” button is on each page of the transcription preview, if I recall correctly. However, a paging button on the layout page isn’t a bad idea at all.

**Comment by thehabes** [comment]
Ok, a new saveLocations() and highlighLocations() now save and handle 8 Annotations (one per each possible location designation) where those Annotations target the line(s) they locate.  The Annotations note what Canvas they belong to in a non-standard way while we think about they best way to do this.  Having them know what Canvas they go to makes them A LOT easier to query for.  See [the PR ](https://github.com/CenterForDigitalHumanities/Glossing-Matthew/pull/38)for examples

I am going to leave that as the core logic behind it, and move on to some UI stuff next.  This is a good point to review the logic behind the new saveLocations() and highlighLocations() and make sure the prototyping is in the correct direction.  

A thought: this seems like a thing where we could have 1 AnnotationPage for "locating" which collects these 8 Annotations.  Maybe then the AnnotationPage could know the Canvas, and each Annotation inside could know the Lines.  Not sure.  We definitely want to know the Canvas though, because users are going through these "a page (canvas) ((folio)) at a time" so we would like a way to query in the context of "the page the user is looking at".
